config/routes.rb
Rails.application.routes.draw do
  
  get 'leaderboard/index'
  get 'map/index'
  root 'home#index'
  get 'companies/index'
  get "/home", to: "home#index"
  get "/home/search", to: "home#search"
  get "posts/to_verify", to: "posts#to_verify"
  post "posts/verify",to: "posts#verify"
  post "awards/buy",to: "awards#buy"
  get 'signup'  => 'users#new'

  devise_scope :user do
     get 'verify', to: 'users/registrations#verify', as: 'verify'
     post 'verify', to: 'users/registrations#verify'
     get 'sign_in', to: 'devise/sessions#new'
     post 'sign_in',to: 'devise/sessions#create'
     get 'users/sign_out',to: 'devise/sessions#destroy'
  end
  resources :follows
  resources :posts do 
    resources :comments
    resources :likes
  end
  resources :challenges do 
    resources :messages
  end
  resources :awards
  resources :join_challenges
  resources :news
  
  
  resources :relationships,only: [:create, :destroy]

  

  
  devise_for :users,controllers: {
        registrations: 'users/registrations',omniauth_callbacks:  'users/omniauth_callbacks'}, :strategy_class => OmniAuth::Strategies::Facebook
resources :users, only: %i[show]
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
	include ActionView::RecordIdentifier
	belongs_to :post
	belongs_to :user
	validates :body,length: { minimum: 1 }

after_create_commit { broadcast_prepend_to [post, :comments], target: "#{dom_id(post)}_comments" }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  rescue_from Pundit::NotAuthorizedError do
    redirect_to root_path, alert: "You aren't allowed to do that"
  end
  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id

    #respond_to do |format|
   @comment.save
=begin       
        format.turbo_stream { render turbo_stream: turbo_stream.replace('comment_form', partial: 'comments/form', locals: { comment: Comment.new }) }
        format.html { render partial: 'comments/form', locals: { comment: Comment.new }}
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('comment_form', partial: 'comments/form', locals: { comment: @comment }) }
        format.html { render partial: 'comments/form', locals: { comment: comment }}
      end
    end
=end
  end

  

  def edit
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)   
  end

  def destroy
        @comment = Comment.find(params[:id])
        authorize @comment
        
        if @comment.destroy
          flash[:notice] = "\"#{@comment.id}\" was successfully deleted."
          redirect_to comments_path,notice: "comment was successfully destroyed."
        else
          flash.now[:alert] = "There was an error deleting the comment."
          render :show
        end
  end
  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>" style="display:flex">

  <p><%= comment.user.username %>: <%= comment.body %> </p>
</div>

app/views/comments/_form.html.erb
    <script>
    $('#form').trigger("reset")
    </script>
<%= turbo_frame_tag "comment_form" do %>
  <%= form_with model: comment, url: post_comments_path(post) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div  class="commentText">
    <%= form.text_field :body %>
    <%= form.submit class:"genButton comments"%>
    </div>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), comment_path(@comment) %>

  <div class="header">
    <h1>Edit comment</h1>
  </div>

  <%= render "form", comment: @comment %>
</main>

app/views/comments/index.html.erb
<main class="container">
  <div class="header">
    <h1>Comments</h1>
    <%= link_to "New quote",
                new_comment_path,
                class: "btn btn--primary" %>
  </div>

  <%= render @comments %>
</main>

app/views/comments/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to comments"), comments_path %>

  <div class="header">
    <h1>New comment</h1>
  </div>

  <%= render "form", comment: @comment %>
</main>