config/routes.rb
Rails.application.routes.draw do
  
  get 'leaderboard/index'
  get 'map/index'
  root 'home#index'
  get 'companies/index'
  get "/home", to: "home#index"
  get "/home/search", to: "home#search"
  get "posts/to_verify", to: "posts#to_verify"
  post "posts/verify",to: "posts#verify"
  post "awards/buy",to: "awards#buy"
  get 'signup'  => 'users#new'

  devise_scope :user do
     get 'verify', to: 'users/registrations#verify', as: 'verify'
     post 'verify', to: 'users/registrations#verify'
     get 'sign_in', to: 'devise/sessions#new'
     post 'sign_in',to: 'devise/sessions#create'
     get 'users/sign_out',to: 'devise/sessions#destroy'
  end
  resources :follows
  resources :posts do 
    resources :comments
    resources :likes
  end
  resources :challenges do 
    resources :messages
  end
  resources :awards
  resources :join_challenges
  resources :news
  
  
  resources :relationships,only: [:create, :destroy]

  

  
  devise_for :users,controllers: {
        registrations: 'users/registrations',omniauth_callbacks:  'users/omniauth_callbacks'}, :strategy_class => OmniAuth::Strategies::Facebook
resources :users, only: %i[show]
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/award.rb
class Award < ApplicationRecord
	belongs_to :user
	has_one_attached :image
end

app/models/challenge.rb
class Challenge < ApplicationRecord
	belongs_to :user
	has_many :join_challenges,dependent: :destroy
	has_many :messages,dependent: :destroy
	attr_accessor :date_time1
	attr_accessor :date_time2
	attr_accessor :date_time3
	def send_messages 
	    @users =Array.new  
	    this.join_challenges.each do |join|
	      @users.push(User.find(join.user_id))
	    end
	    @users.each do |user|
	      url = URI("https://inteltech.p.rapidapi.com/send.php")

	      http = Net::HTTP.new(url.host, url.port)
	      http.use_ssl = true
	      http.verify_mode = OpenSSL::SSL::VERIFY_NONE

	      request = Net::HTTP::Post.new(url)
	      request["content-type"] = 'application/x-www-form-urlencoded'
	      request["X-RapidAPI-Key"] = 'dd42f26b3emshac94e324c873f7bp132f7cjsn86b7b4d80c16'
	      request["X-RapidAPI-Host"] = 'inteltech.p.rapidapi.com'
	      request.body = "sms=%2B"+user.num_tel.tr('+', '')+"&message=Upload%20pictures%20and%20videos%20of%20your%20challenge%20by%20clicking%20on%20this%20link&senderid=MyCompany&schedule=1377959755&return=http%3A%2F%2Fyourwebsite.com&key=D63A0EB8-E2C9-28F5-B5C3-65368D003C8F&username=gabrincarbone%40gmail.com"

	      response = http.request(request)
	      puts response.read_body
	    end 
  end
	handle_asynchronously :send_messages,:run_at => @date_time1
    handle_asynchronously :send_messages,:run_at => @date_time2
    handle_asynchronously :send_messages,:run_at => @date_time3
    def assign_points
      ratio  = self.raggio.to_f / self.num_partecipanti * self.durata
      self.points = ratio
      self.save
   end 
 
end

app/models/comment.rb
class Comment < ApplicationRecord
	include ActionView::RecordIdentifier
	belongs_to :post
	belongs_to :user
	validates :body,length: { minimum: 1 }

after_create_commit { broadcast_prepend_to [post, :comments], target: "#{dom_id(post)}_comments" }
end

app/models/current.rb
 class Current < ActiveSupport::CurrentAttributes
    attribute :user
  end

app/models/join_challenge.rb
class JoinChallenge < ApplicationRecord
	belongs_to :user
	belongs_to :challenge
	validates :user_id, presence: true
  	validates :challenge_id,presence:true
  	
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  after_create_commit { broadcast_prepend_to [post, :likes], target: "#{dom_id(post)}_likes" }
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :challenge
	belongs_to :user
	validates :msg_txt,length: { minimum: 1 }
	after_create_commit { broadcast_append_to self.challenge }
end

app/models/news.rb
class News < ApplicationRecord
	validates :title,uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many_attached :images
	has_many :likes, dependent: :destroy
	has_many :comments,dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
  	belongs_to :followed, class_name: "User"
  	validates :follower_id, presence: true
  	validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord  

  has_one_attached :image
  validates :role, inclusion: { in: %w(level0 level1 level2 company admin),
   message: "%{value} is not a valid role" }
  validates :username, presence: true, uniqueness: true
  validates :email,presence:true,uniqueness:true
  validates :num_tel, presence: true, uniqueness: true
  enum :role ,{:level0 => 0,:level1=>1, :level2  => 2 ,:company => 3,:admin => 4}
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :posts, -> { order(created_at: :desc) },dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :join_challenges,dependent: :destroy
  has_many :messages,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  def to_json(options={})
    options[:except] ||= [:verified]
    super(options)
  end
  

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]
      ["extra"]["raw_info"]
         user.email = data["email"] if user.email.blank?
      end
    end
  end
   # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action :authenticate_user!
  protect_from_forgery prepend: true
  def index
    @post = Post.new 
    @follows  = current_user.following.select(:followed_id)
    @timeline_posts = Post.where(verified: true).where("user_id in (?)", @follows).order(created_at: :desc)
  end
  def search
    if params[:search].blank?
      redirect_to home_path and return
    else
      @parameter = params[:search].downcase
      @results = User.all.where("lower(username) LIKE :search", search: "%#{@parameter}%")
    end
  end

end

app/controllers/map_controller.rb
class MapController < ApplicationController
  before_action :authenticate_user!
  def index
    @query =Challenge.select(:luogo,:raggio)
    @other_challenges = Array.new
    @query.each do |t|
      @lat = t.luogo.split(',')[0]
      @long = t.luogo.split(',')[1]
      @rad  =t.raggio.to_s
      @other_challenges.push (@lat+':'+@long+':'+@rad)
    end
    @other_challenges = @other_challenges.to_json.html_safe

    
    @query=JoinChallenge.select(:challenge_id).where.not(user_id:current_user.id).distinct
    @to_join = Challenge.where('id in (?)',@query)
      @join_challenge = JoinChallenge.new
    @challenge = Challenge.new
    
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/home/_sidebar.html.erb
<%= stylesheet_link_tag "sidebar" %>
  <!-- Sidebar -->
  <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-green">
    <div class="position-sticky">
      <div id="profile_picture">
        <%if current_user.image.attached? %>
        <%= image_tag(current_user.image)%>
        <% end%>
      <%= link_to current_user.username, current_user, class: "genText" %>
      </div>
      <div id="logo">
          <i class="fas fa-chart-bar fa-fw me-3"></i><%=link_to 'PickItUp',root_path,:method => :get,class: "title" %>
            
      </div>
      <div class="list-group list-group-flush mx-3 mt-4">
        <%= form_tag(home_search_path, :method => "get") do %>
        <div class="input-group">
          <%= search_field_tag :search,params[:search],placeholder: "Search User ", class: "form-control" %>
          <div class="input-group-btn">
            <%= button_tag "Search" ,:class => 'btn btn-info glyphicon glyphicon-search',:name => nil %>
          </div>
        <% end %>
        
            <i class="fas fa-chart-bar fa-fw me-3"></i><%=link_to 'LeaderBoard',leaderboard_index_path,:method => :get,class: "list-group-item list-group-item-action py-2 ripple" %>
            <br>
            <i class="fas fa-chart-bar fa-fw me-3"></i><%=link_to 'Map',map_index_path,:method => :get,class: "list-group-item list-group-item-action py-2 ripple" ,data: { turbo: false} %>
            <br>
            <i class="fas fa-chart-bar fa-fw me-3"></i><%=link_to 'News',news_index_path,:method => :get,class: "list-group-item list-group-item-action py-2 ripple" ,data: { turbo: false} %>
            <br>
            <i class="fas fa-chart-bar fa-fw me-3"></i><%=link_to 'Challenges',challenges_path,:method => :get,class: "list-group-item list-group-item-action py-2 ripple"  %>
            <br>
            
            <i class="fas fa-chart-bar fa-fw me-3"></i><%=link_to 'Sponsors',companies_index_path,:method => :get,class: "list-group-item list-group-item-action py-2 ripple"  %>
            <br>
            <i class="fas fa-globe fa-fw me-3"></i><%= link_to 'Settings',edit_user_registration_path,:method => :get, class: "list-group-item list-group-item-action py-2 ripple" %></br>
            <%if current_user.role == 'admin' %>
            <i class="fas fa-globe fa-fw me-3"></i><%= link_to 'Verify',posts_to_verify_path,:method => :get, class: "list-group-item list-group-item-action py-2 ripple" %></br>
            <% end %>
            <i class="fas fa-chart-bar fa-fw me-3"></i><%=link_to 'Awards',awards_path,:method => :get,class: "list-group-item list-group-item-action py-2 ripple"  %>
            <br>
            <i class="fas fa-globe fa-fw me-3" ></i><%= link_to 'Logout',
                destroy_user_session_path, method: :delete,class: "list-group-item list-group-item-action py-2 ripple"%>
            
        
            
        
      </div>
    </div>
  </nav>
  <!-- Sidebar -->

app/views/home/index.html.erb
<% content_for :body do %>
    <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '2366483176861220',
      xfbml      : true,
      version    : 'v16.0'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<% end %>
<div id= "timeline">

<% if Pundit.policy(Current.user,@post).create? %>	
	
	
	<%= simple_form_for @post, html: { class: "myContainer" },action: "/posts" do |f| %>
  
  <h2 class="postTitle">Write what you're thinking &nbsp;</h2>
  <%= f.input :written_text, input_html: { autofocus: true }, wrapper: false, label: false, class:"postText"%>
  <div style="margin:auto; display: grid; grid-auto-flow: column;">
  <%= f.input :images, multiple: true ,value: @post.images,required: true, label: false, html: { style: "" } %>
  <%= f.submit 'Post',class: "genButton", style:"margin-right:10px"%>
  </div>
<% end %>
<%end %>
	<%= render @timeline_posts %>
	
  
</div>

app/views/home/search.html.erb
<div class ="leaderboard">
<table>
  <thead>
    <tr>
      <th style="width: 100%;">Risultati della ricerca</th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |user| %>
    <!-- class adult to any table rows for movies rated other than G or PG -->
      <tr>
        <td><%= link_to  user.username, user, data:{turbo: false} , class:"genText", style:"align:middle; max-width: 80%"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>