config/routes.rb
Rails.application.routes.draw do
  
  get 'leaderboard/index'
  get 'map/index'
  root 'home#index'
  get 'companies/index'
  get "/home", to: "home#index"
  get "/home/search", to: "home#search"
  get "posts/to_verify", to: "posts#to_verify"
  post "posts/verify",to: "posts#verify"
  post "awards/buy",to: "awards#buy"
  get 'signup'  => 'users#new'

  devise_scope :user do
     get 'verify', to: 'users/registrations#verify', as: 'verify'
     post 'verify', to: 'users/registrations#verify'
     get 'sign_in', to: 'devise/sessions#new'
     post 'sign_in',to: 'devise/sessions#create'
     get 'users/sign_out',to: 'devise/sessions#destroy'
  end
  resources :follows
  resources :posts do 
    resources :comments
    resources :likes
  end
  resources :challenges do 
    resources :messages
  end
  resources :awards
  resources :join_challenges
  resources :news
  
  
  resources :relationships,only: [:create, :destroy]

  

  
  devise_for :users,controllers: {
        registrations: 'users/registrations',omniauth_callbacks:  'users/omniauth_callbacks'}, :strategy_class => OmniAuth::Strategies::Facebook
resources :users, only: %i[show]
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/models/award.rb
class Award < ApplicationRecord
	belongs_to :user
	has_one_attached :image
end

app/controllers/award_controller.rb
class AwardController < ApplicationController
  before_action :set_award, only: [:show, :edit, :update, :destroy]
  rescue_from Pundit::NotAuthorizedError do
    redirect_to root_path, alert: "You aren't allowed to do that"
  end
  def index
    @awards = Award.all
  end

  def show
  end

  def new
    @award = Award.new
    authorize @award
  end

  def create
    @award = Award.new(award_params)
    authorize @award
    if @award.save
      redirect_to awards_path, notice: "award was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    @award = Award.find(params[:id])
    authorize @award
    if @award.update(award_params)
      redirect_to awards_path, notice: "award was successfully updated."
    else
      render :edit
    end
  end

  def destroy
        @award = Award.find(params[:id])
        authorize @award
        
        if @award.destroy
          flash[:notice] = "\"#{@award.id}\" was successfully deleted."
          redirect_to awards_path,notice: "award was successfully destroyed."
        else
          flash.now[:alert] = "There was an error deleting the award."
          render :show
        end
  end
  private

  def set_award
    @award = Award.find(params[:id])
  end

  def award_params
    params.require(:award).permit(:nome)
  end

end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_award, only: [:show, :edit, :update, :destroy]
  before_action :set_award_buy, only: [:buy]
  rescue_from Pundit::NotAuthorizedError do
    redirect_to root_path, alert: "You aren't allowed to do that"
  end
  def index
    @awards = Award.all.order(created_at: :desc)
    @award = Award.new
  end

  def show
  end

  def new
    @award = Award.new
    
  end

  def create
    @award = Award.new(award_params)
    authorize @award
    @award.save
    redirect_to awards_path, notice: "award was successfully created."
  end

  def edit
  end

  def update
    @award = Award.find(params[:id])
    authorize @award
    if @award.update(award_params)
      redirect_to awards_path, notice: "award was successfully updated."
    else
      render :edit
    end
  end

  def destroy
        @award = Award.find(params[:id]) 
        if @award.destroy
          flash[:notice] = "\"#{@award.id}\" was successfully deleted."
          redirect_to awards_path,notice: "award was successfully destroyed."
        else
          flash.now[:alert] = "There was an error deleting the award."
          render :show
        end
  end
  def buy
    @award.left -= 1
    if @award.left == 0
      @award.destroy
    else
      @award.save
    end
    if current_user.points
      current_user.points -= @award.price
      if current_user.points <= 0
        flash[:notice] = "You don't have enough points to buy this award!Go do another challenge"
      else
        current_user.save
      end
    end
    redirect_to awards_path

  end
  private

  def set_award
    @award = Award.find(params[:id])
  end
  def set_award_buy
    @award = Award.find(params[:format])
  end
  def award_params
    params.require(:award).permit(:user_id,:image,:price,:description,:left)
  end

end

app/views/awards/_award.html.erb
<%= stylesheet_link_tag "awards" %>

<div class="award">
<div class="left">
  <h2 class="awardTitle"><%= award.description %> </h2>
  <%if award.image.attached?%>
  <%= image_tag(award.image)%>
  <%else%>
  <div class= "filler"></div>
  <%end%>
</div>  

<div style="max-width=25%">
  <div class="footer" style="display:column-flex;">
      <div><p> Quantity left:<%= award.left %></div>
      <div>PRICE: <%= award.price %> points</div>
  </div>
  <div class="award__actions">
    
      <%= button_to "BUY", awards_buy_path(award.id),method: :post,id:award.id ,class:"genButton", style:"height:40px;width:40px;border-radius:.25rem"%>
    <% if Pundit.policy(Current.user,award).destroy? %>
      <%= button_to "",
                  award_path(award),
                  method: :delete,
                  class: "btn btn--light delete", style:"margin-top:0" %>
    <% end %>
    
    <% if Pundit.policy(Current.user,award).update? %>
      <%= link_to "Edit",
                 edit_award_path(award),
                class: "btn btn--light" %>
    <% end %>
  </div>
  </div>
</div>

app/views/awards/_form.html.erb
<%= simple_form_for award, html: { class: "award form" } do |f| %>
  <% if award.errors.any? %>
    <div class="error-message">
      <%= award.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :description, input_html: { autofocus: true } %>
  <%= f.input :price, input_html: { autofocus: true } %>
  <%= f.input :left, input_html: { autofocus: true } %>
  <%= f.input :image, input_html: { autofocus: true } %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/awards/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), award_path(@award) %>

  <div class="header">
    <h1>Edit award</h1>
  </div>

  <%= render "form", award: @award %>
</main>

app/views/awards/index.html.erb
 <h2 class = "genTitle" style="margin-left:300px;border-top-right-radius:5px;margin-bottom:50px" >New award</h2>
<main class="containerAwards">
<% if Pundit.policy(Current.user,@award).create? %>
  <%= simple_form_for @award, html: { class: "award form" } do |f| %>
  <% if @award.errors.any? %>
    <div class="error-message">
      <%= @award.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :description, input_html: { autofocus: true } %>
  <%= f.input :price, input_html: { autofocus: true } %>
  <%= f.input :left, input_html: { autofocus: true } %>
  <%= f.input :image, input_html: { autofocus: true } %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit class: "genButton", style:"
  margin-left: 130px;
  margin-bottom: 30px;
  font-size: 40px;" %>
<% end %>
<% end %>
</main> 
<h2 class = "genTitle" style="margin-left:300px;border-top-right-radius:5px;margin-bottom:50px;margin-top:30px" >Awards</h2>
  <%= render @awards %>

app/views/awards/new.html.erb
<main class="containerAwards">
  <%= link_to sanitize("&larr; Back to awards"), awards_path %>

  <div class="header">
   
  </div>
  <%= render "form", award: @award %>
</main>