config/routes.rb
Rails.application.routes.draw do
  
  get 'leaderboard/index'
  get 'map/index'
  root 'home#index'
  get 'companies/index'
  get "/home", to: "home#index"
  get "/home/search", to: "home#search"
  get "posts/to_verify", to: "posts#to_verify"
  post "posts/verify",to: "posts#verify"
  post "awards/buy",to: "awards#buy"
  get 'signup'  => 'users#new'

  devise_scope :user do
     get 'verify', to: 'users/registrations#verify', as: 'verify'
     post 'verify', to: 'users/registrations#verify'
     get 'sign_in', to: 'devise/sessions#new'
     post 'sign_in',to: 'devise/sessions#create'
     get 'users/sign_out',to: 'devise/sessions#destroy'
  end
  resources :follows
  resources :posts do 
    resources :comments
    resources :likes
  end
  resources :challenges do 
    resources :messages
  end
  resources :awards
  resources :join_challenges
  resources :news
  
  
  resources :relationships,only: [:create, :destroy]

  

  
  devise_for :users,controllers: {
        registrations: 'users/registrations',omniauth_callbacks:  'users/omniauth_callbacks'}, :strategy_class => OmniAuth::Strategies::Facebook
resources :users, only: %i[show]
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/models/join_challenge.rb
class JoinChallenge < ApplicationRecord
	belongs_to :user
	belongs_to :challenge
	validates :user_id, presence: true
  	validates :challenge_id,presence:true
  	
end

app/controllers/join_challenges_controller.rb
class JoinChallengesController < ApplicationController
  #before_action :set_join_challenge, only: [:show, :edit, :update, :destroy]
  rescue_from Pundit::NotAuthorizedError do
    redirect_to challenges_path, alert: "You aren't allowed to do that"
  end
  def index
    @join_challenges = JoinChallenge.all
  end

  def show
  end

  def new
  end

  def create
    @join_challenge = JoinChallenge.new
    @challenge_id = params[:join_challenge][:challenge_id]
    @join_challenge.challenge_id = @challenge_id
    @join_challenge.user_id = current_user.id
    @challenge = Challenge.find(@challenge_id)
    @challenge.num_partecipanti += 1
    if @challenge.durata != nil
      @challenge.assign_points
    end
    if @join_challenge.save
      @post = Post.create(user_id: current_user.id,challenge_id: @challenge_id )
      if @post.persisted?
        redirect_to challenges_path,challenge_id: params[:id], notice: "You can chat with other Challenge memebers now"
      end
    else

      redirect_to root_path, notice: "join challenge was not created successfully"
    end
  end

  def edit
  end

  def update
    @join_challenge = JoinChallenge.find(params[:id])
    authorize @join_challenge
    if @join_challenge.update(join_challenge_params)
      redirect_to join_challenges_path, notice: "join_challenge was successfully updated."
    else
      render :edit
    end
  end

  def destroy
        @join_challenge = JoinChallenge.find(params[:id])
        
        
        if @join_challenge.destroy
          flash[:notice] = "\"#{@join_challenge.id}\" was successfully deleted."
          redirect_to join_challenges_path,notice: "join_challenge was successfully destroyed."
        else
          flash.now[:alert] = "There was an error deleting the join_challenge."
          render :show
        end
  end
  private

 
  

end

app/views/join_challenges/_form.html.erb
<%= simple_form_for @join_challenge, html: { class: "join_challenge form" } do |f| %>
  <% if @join_challenge.errors.any? %>
    <div class="error-message">
      <%= @join_challenge.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.hidden_field :challenge_id,value: params[:id] %>
  <%= f.hidden_field :user_id,value: current_user.id %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/join_challenges/_join_challenge.html.erb
<div class="join_challenge">
  <%= link_to join_challenge.body, join_challenge_path(join_challenge) %>
  <div class="join_challenge__actions">
    <%= button_to "",
                  join_challenge_path(join_challenge),
                  method: :delete,
                  class: "btn btn--light delete" %>
    <%= link_to "Edit",
                edit_join_challenge_path(join_challenge),
                class: "btn btn--light" %>
  </div>
</div>

app/views/join_challenges/_new.html.erb
<main class="container">
  <%= render "join_challenges/form", join_challenge: @join_challenge %>
</main>

app/views/join_challenges/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), join_challenge_path(@join_challenge) %>

  <div class="header">
    <h1>Edit join_challenge</h1>
  </div>

  <%= render "form", join_challenge: @join_challenge %>
</main>

app/views/join_challenges/index.html.erb
<main class="container">
  <div class="header">
    <h1>join_challenges</h1>
    <%= link_to "New quote",
                new_join_challenge_path,
                class: "btn btn--primary" %>
  </div>

  <%= render @join_challenges %>
</main>